//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDao.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class getpwdlog
    {
        public long id { get; set; }
        public int uid { get; set; }
        public string nick_name { get; set; }
        public string ip_address { get; set; }
        public System.DateTime log_time { get; set; }
    }
}
