//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDao.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WeiQingEntities : DbContext
    {
        public WeiQingEntities()
            : base("name=WeiQingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<getpwdlog> getpwdlog { get; set; }
        public virtual DbSet<bazijianpi> bazijianpi { get; set; }
        public virtual DbSet<login_log> login_log { get; set; }
        public virtual DbSet<title> title { get; set; }
        public virtual DbSet<tiezi> tiezi { get; set; }
        public virtual DbSet<tzreply> tzreply { get; set; }
        public virtual DbSet<tiezi_jubao> tiezi_jubao { get; set; }
        public virtual DbSet<notice> notice { get; set; }
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<liuyanban> liuyanban { get; set; }
    }
}
